# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nmo1vfIPS0pecivHRbFtBlbsM46qrIv
"""

import bs4
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup

# name the output file to write to local disk
out_filename = "patient_reviews.csv"
# header of csv file to be written
headers = "review \n"

# opens file, and writes headers
f = open(out_filename, "w")
f.write(headers)

my_url = 'https://www.scoi.com/about-us/patient-reviews?page='

for page_number in range(1, 28):
  uClient = uReq(my_url + str(page_number))
  page_html = uClient.read()
  uClient.close()
  page_soup = soup(page_html, "html.parser")
  review_containers = page_soup.find_all("span",{"class":"field-content"})
  for review_container in review_containers:
    review = review_container.text.strip()
    f.write(review.replace(",", "|") + "\n")